from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views, apis

urlpatterns = [
    path('', views.index, name='index'),
    path('pages/solicitud.html', views.solicitud, name='solicitud'),
    path('pages/registro.html', views.registro, name='registro'),
    path('pages/password-recovery.html', views.password_recovery, name='password-recovery'),
    path('pages/terms.html', views.terms, name='terms'),
    path('pages/politics.html', views.politics, name='politics'),
    path('profile/mis-datos.html', views.mis_datos, name='profile/mis-datos'),
    path('profile/mis-solicitudes.html', views.mis_solicitudes, name='profile/mis-solicitudes'),
    path('profile/causas.html', views.causas, name='causas'),
    path('profile/finanzas.html', views.finanzas, name='finanzas'),
    path('juridic-tecnic/jt-solicitud.html', views.jt_solicitud, name='jt-solicitud'),
    path('juridic-tecnic/jt-info.html', views.jt_info, name='jt-info'),
    path('juridic-tecnic/jt-view-solicitud.html', views.jt_view_solicitud, name='jt-view-solicitud'),
    path('juridic-tecnic/budget.html', views.budget, name='budget'),
    path('juridic-tecnic/jt-pays.html', views.jt_pays, name='jt-pays'),
    path('profile/view-causas.html', views.view_causas, name='view-causas'),
    path('profile/ver-solicitud/<str:id_solicitud>', views.ver_solicitud, name='profile/ver-solicitud'),
    path('layers/layer-view.html', views.layer_view, name='layer-view'),
    path('layers/layer-causas.html', views.layer_causas, name='layer-causas'),
    path('layers/layer-view-diligencias.html', views.layer_view_diligencias, name='layer-view-diligencias'),
    path('layers/layer-view-causas.html', views.layer_view_causas, name='layer-view-causas'),
    path('layers/layer-diligencias.html', views.layer_diligencias, name='layer-diligencias'),
    path('administrator/admin-view.html', views.admin_view, name='admin-view'),
    path('administrator/admin-report-mensual.html', views.admin_report_mensual, name='admin-report-mensual'),
    path('administrator/admin-report-anual.html', views.admin_report_anual, name='admin-report-anual'),
    path('api/registro', csrf_exempt(apis.registrarse), name='api/registro'),
    path('api/login', csrf_exempt(apis.iniciar_sesion), name='api/login'),
    path('api/logout', csrf_exempt(apis.cerrar_sesion), name='api/logout'),
    path('api/authenticated', csrf_exempt(apis.is_aunthenticated), name='api/authenticated'),
    path('api/profile/mis-datos', csrf_exempt(apis.guardar_mis_datos), name='api/profile/mis-datos'),
    path('api/solicitud/enviar', csrf_exempt(apis.enviar_solicitud), name='api/solicitud/enviar'),
]