# Generated by Django 5.0.6 on 2024-06-27 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexusservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='id_rol', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria_producto',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', default=1, on_delete=django.db.models.deletion.CASCADE, to='lexusservice.rol'),
        ),
        migrations.DeleteModel(
            name='CategoriaProducto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
