# Generated by Django 5.0.6 on 2024-06-27 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexusservice', '0002_rol_remove_producto_id_categoria_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='lexusservice.rol'),
        ),
    ]
