# Generated by Django 5.0.6 on 2024-06-27 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexusservice', '0003_alter_usuario_id_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.CASCADE, to='lexusservice.rol'),
        ),
    ]
