# Generated by Django 5.0.6 on 2024-06-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexusservice', '0004_alter_usuario_id_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
