# Generated by Django 5.0.6 on 2024-07-18 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexusservice', '0008_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEstado',
            fields=[
                ('id', models.AutoField(db_column='id_estado', primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='servicio',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, to='lexusservice.servicio')),
                ('usuario', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='lexusservice.solicitudestado')),
            ],
        ),
    ]
