# Generated by Django 5.0.6 on 2024-07-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexusservice', '0009_solicitudestado_alter_servicio_managers_solicitud'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
